-- Migration: Create core TRAVELAMAL CRM tables (idempotent)
-- Date: 2026-04-22

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  email text NOT NULL,
  name text NOT NULL,
  role text DEFAULT 'Employé',
  avatar_url text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_role_check CHECK (role IN ('Admin','Employé'));

-- clients
CREATE TABLE IF NOT EXISTS public.clients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sequential_number integer GENERATED BY DEFAULT AS IDENTITY,
  full_name text NOT NULL,
  profession text,
  marital_status text,
  id_card_number text,
  phone_primary text NOT NULL,
  phone_secondary text,
  email text,
  birth_date date,
  nationality text,
  address_street text,
  address_city text,
  address_governorate text,
  folder_opening_date date,
  passport_number text,
  passport_expiry date,
  passport_alert_done boolean DEFAULT false,
  b3_expiry date,
  b3_alert_done boolean DEFAULT false,
  embassy_registration_date date,
  travel_alert_done boolean DEFAULT false,
  service text,
  color_tag text NOT NULL DEFAULT '#6B7280',
  status text DEFAULT 'Nouveau',
  total_amount numeric(10,3) DEFAULT 0,
  amount_paid numeric(10,3) DEFAULT 0,
  refund_amount numeric(10,3) DEFAULT 0,
  amount_remaining numeric(10,3) GENERATED ALWAYS AS (total_amount - amount_paid) STORED,
  payment_status text GENERATED ALWAYS AS (
    CASE
      WHEN amount_paid >= total_amount AND total_amount > 0 THEN 'Complet'
      WHEN amount_paid > 0 THEN 'Partiel'
      ELSE 'Non paye'
    END
  ) STORED,
  payment_method text,
  appointment_date timestamptz,
  travel_date date,
  notes text,
  created_at timestamptz DEFAULT now(),
  created_by uuid REFERENCES public.profiles(id),
  responsible_employee uuid REFERENCES public.profiles(id)
);

ALTER TABLE public.clients DROP CONSTRAINT IF EXISTS clients_status_check;
ALTER TABLE public.clients ADD CONSTRAINT clients_status_check
  CHECK (status IN ('Nouveau','En cours','Complété','Refusé','Annulé'));

ALTER TABLE public.clients DROP CONSTRAINT IF EXISTS clients_marital_status_check;
ALTER TABLE public.clients ADD CONSTRAINT clients_marital_status_check
  CHECK (marital_status IN ('Célibataire','Marié(e)','Divorcé(e)','Veuf/Veuve') OR marital_status IS NULL);

ALTER TABLE public.clients DROP CONSTRAINT IF EXISTS clients_payment_method_check;
ALTER TABLE public.clients ADD CONSTRAINT clients_payment_method_check
  CHECK (payment_method IN ('Espèces','Virement','Chèque','Carte') OR payment_method IS NULL);

-- payments
CREATE TABLE IF NOT EXISTS public.payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES public.clients(id) ON DELETE CASCADE,
  amount numeric(10,3) NOT NULL,
  payment_date date DEFAULT current_date,
  method text,
  recorded_by uuid REFERENCES public.profiles(id),
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_method_check;
ALTER TABLE public.payments ADD CONSTRAINT payments_method_check
  CHECK (method IN ('Espèces','Virement','Chèque','Carte') OR method IS NULL);

-- documents
CREATE TABLE IF NOT EXISTS public.documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES public.clients(id) ON DELETE CASCADE,
  document_type text,
  file_url text NOT NULL,
  file_name text,
  upload_date timestamptz DEFAULT now(),
  expiry_date date,
  status text DEFAULT 'Présent',
  uploaded_by uuid REFERENCES public.profiles(id)
);

ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_document_type_check;
ALTER TABLE public.documents ADD CONSTRAINT documents_document_type_check
  CHECK (document_type IN (
    'Passeport','CIN','Photo','Acte de naissance','Fiche familiale',
    'Justificatif bancaire','Assurance','Réservation vol','Autre'
  ) OR document_type IS NULL);

ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_status_check;
ALTER TABLE public.documents ADD CONSTRAINT documents_status_check
  CHECK (status IN ('Présent','Manquant','Expiré') OR status IS NULL);

-- expenses
CREATE TABLE IF NOT EXISTS public.expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  amount numeric(10,3) NOT NULL,
  description text NOT NULL,
  proof_url text,
  client_id uuid REFERENCES public.clients(id),
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- activities
CREATE TABLE IF NOT EXISTS public.activities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid REFERENCES public.clients(id) ON DELETE CASCADE,
  action_type text,
  description text NOT NULL,
  performed_by uuid REFERENCES public.profiles(id),
  action_date timestamptz DEFAULT now()
);

ALTER TABLE public.activities DROP CONSTRAINT IF EXISTS activities_action_type_check;
ALTER TABLE public.activities ADD CONSTRAINT activities_action_type_check
  CHECK (action_type IN ('Création','Modification','Paiement','Document','Statut','Note') OR action_type IS NULL);

-- Helper function for RLS
CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- Trigger function for new users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'name', ''), split_part(COALESCE(NEW.email, 'user@example.com'), '@', 1)),
    CASE
      WHEN NEW.raw_user_meta_data->>'role' IN ('Admin','Employé') THEN NEW.raw_user_meta_data->>'role'
      ELSE 'Employé'
    END
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'on_auth_user_created'
  ) THEN
    CREATE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
  END IF;
END $$;

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

COMMIT;
